#!/usr/bin/python

import sys
import time
import os

def copy_no_rate(from_, to_):
  while True:
    b = from_.read(16384)
    if not b:
      return
    to_.write(b)

def copy(from_, to_, rate=None):
  if rate is None:
    return copy_no_rate(from_, to_)

  divisor = 4.0

  time_unit = 1 / divisor
  rate = rate / divisor
  while True:
    t = time.time() + time_unit

    window = rate
    while window > 0:
      b = from_.read(16384)
      if not b:
        return
      to_.write(b)
      window-=len(b)

    wait_for = t - time.time()
    if wait_for > 0:
      time.sleep(wait_for)

def main(target_dir, suffix, max_entries, rate=None, hourly=False):
  if hourly:
    pattern = "%Y%m%d-%H"
  else:
    pattern = "%Y%m%d"

  target_file = os.path.join(target_dir, "%s%s" % (time.strftime(pattern, time.gmtime()), suffix))

  if not os.path.exists(target_dir):
    os.makedirs(target_dir)

  try:
    f = open(target_file, "wb")
    try:
      copy(sys.stdin, f, rate)
    finally:
      f.close()
  finally:
    l = sorted(os.listdir(target_dir))
    while len(l) > max_entries:
      os.unlink(os.path.join(target_dir, l.pop(0)))

if __name__ == "__main__":
  args = sys.argv[1:]

  hourly = False
  if args[:1] == ["-h"]:
    args.pop(0)
    hourly = True

  if len(args) < 3:
    print >>sys.stderr, "syntax: %s ?-h (hourly)? [target dir] [backup suffix] [number of entries to keep] ?rate limit in kb/s?" % sys.argv[0]
    sys.exit(1)

  if len(args) == 4:
    rate = int(args[3]) * 1024
  else:
    rate = None

  main(target_dir=args[0], suffix=args[1], max_entries=int(args[2]), rate=rate, hourly=hourly)
