#!/usr/bin/python3.7

import sys
import time
import os

class RateLimiter:
  WINDOWS = 10
  def __init__(self, max_rate_bps):
    self.rate = rate
    self.check_every = rate // self.WINDOWS
    self.last_time = time.time()
    self.bytes = 0

  def data(self, l):
    self.bytes+=l
    if self.bytes < self.check_every:
      return

    now = time.time()
    delta_time = now - self.last_time
    expected = self.rate * delta_time

    if self.bytes > expected:
      sleep_for = (self.bytes - expected) / self.rate
      time.sleep(sleep_for)
      now = time.time()

    self.last_time = now
    self.bytes = 0

def copy(from_, to_, rate=None):
  if rate:
    throttle = RateLimiter(rate).data
  else:
    throttle = lambda x: None

  while True:
    b = from_.read(16384)
    if not b:
      return
    to_.write(b)
    throttle(len(b))

def main(target_dir, suffix, max_entries, rate=None, hourly=False):
  if hourly:
    pattern = "%Y%m%d-%H"
  else:
    pattern = "%Y%m%d"

  target_file = os.path.join(target_dir, "%s%s" % (time.strftime(pattern, time.gmtime()), suffix))

  if not os.path.exists(target_dir):
    os.makedirs(target_dir)

  try:
    with open(target_file, "wb") as f:
      copy(sys.stdin.buffer, f, rate)
      os.fsync(f.fileno())
  finally:
    l = sorted(os.listdir(target_dir))
    while len(l) > max_entries:
      os.unlink(os.path.join(target_dir, l.pop(0)))

if __name__ == "__main__":
  args = sys.argv[1:]

  hourly = False
  if args[:1] == ["-h"]:
    args.pop(0)
    hourly = True

  if len(args) < 3:
    print("syntax: %s ?-h (hourly)? [target dir] [backup suffix] [number of entries to keep] ?rate limit in kb/s?" % sys.argv[0], file=sys.stderr)
    sys.exit(1)

  if len(args) == 4:
    rate = int(args[3]) * 1024
  else:
    rate = None

  main(target_dir=args[0], suffix=args[1], max_entries=int(args[2]), rate=rate, hourly=hourly)
