#!/usr/bin/python
import sys
import shlex
import os
import traceback

easybackup_path = os.path.join(os.path.dirname(sys.argv[0]), "easybackup")

if len(sys.argv) < 3 or sys.argv[1] != "-c":
  print >>sys.stderr, "this account is for easybackup only"
  sys.exit(1)

args = shlex.split(sys.argv[2])
if args[0] != easybackup_path:
  print >>sys.stderr, "unable to execute -- shell mismatch"
  sys.exit(1)

try:
  os.execv(easybackup_path, [easybackup_path] + args[1:])
except Exception, e:
  # prints to stderr
  traceback.print_exc()
finally:
  sys.exit(1)
